# Numpy

In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
np_arr = np.array([1, 2, 3, 4])

In [4]:
value_list = [1, 2, 3, 4]

In [5]:
2*value_list

[1, 2, 3, 4, 1, 2, 3, 4]

In [6]:
2*np_arr

array([2, 4, 6, 8])

In [7]:
np_arr/2

array([0.5, 1. , 1.5, 2. ])

In [8]:
np_arr + np_arr

array([2, 4, 6, 8])

In [9]:
np_arr - np_arr

array([0, 0, 0, 0])

In [10]:
np_arr.mean()

2.5

In [11]:
np_arr.std()

1.118033988749895

In [12]:
np_arr.max()

4

In [13]:
np_arr.min()

1

In [18]:
v1 = np.array([1, 2])
v2 = np.array([0, 1])

In [19]:
v1 * v2

array([0, 2])

In [56]:
v1 = np.array([1, 2, 1])
v2 = np.array([1, 1, 2])
v1.dot(v2)   

# = 1*1 + 2*1 + 1*2 = 1 + 2 + 2 = 5

5

In [57]:
v1.shape

(3,)

In [58]:
prim1 = np.array([1, 2, 3, 4, 5, 6])

In [59]:
prim1

array([1, 2, 3, 4, 5, 6])

In [60]:
prim1.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
matrix_list = [[1, 2, 3],
               [4, 5, 6]]

In [27]:
matrix = np.array(matrix_list)

In [29]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
matrix.shape

(2, 3)

In [32]:
matrix.shape[0]

2

In [33]:
matrix.shape[1]

3

In [31]:
matrix[0]

array([1, 2, 3])

In [36]:
matrica = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [0, 1, 9],
    [8, 7, 2]
])


In [39]:
matrica[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [40]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

In [41]:
A + B

array([[ 6,  8],
       [10, 12]])

In [42]:
A * B

array([[ 5, 12],
       [21, 32]])

In [43]:
A.dot(B)

array([[19, 22],
       [43, 50]])

In [44]:
2*A

array([[2, 4],
       [6, 8]])

In [45]:
A - 1

array([[0, 1],
       [2, 3]])

In [50]:
A/2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [46]:
A_inv = np.linalg.inv(A)

In [47]:
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [48]:
A_inv.dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [49]:
A.dot(A_inv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
A.dot(np.array([1, 2]))

array([ 5, 11])

In [55]:
A

array([[1, 2],
       [3, 4]])

In [54]:
A.T

array([[1, 3],
       [2, 4]])

# Pandas

In [62]:
import pandas as pd